import { Link, useNavigate, useRouterState } from "@tanstack/react-router";
import { useEffect, type ReactNode } from "react";
import { LogOut, Package, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { hydratePlatform, PHARMACY_NAMES, platformActions, usePlatform } from "@/lib/platform/store";

export function PharmacyShell({ children, title }: { children:ReactNode; title:string }) {
  const session=usePlatform(s=>s.pharmacySession); const path=useRouterState({select:s=>s.location.pathname}); const nav=useNavigate();
  useEffect(()=>hydratePlatform(),[]); const pharmacy=session?.pharmacyId?PHARMACY_NAMES[session.pharmacyId]:"South End Pharmacy";
  return <div className="admin-scope min-h-screen bg-canvas text-ink"><header className="border-b border-ink/10 bg-white"><div className="mx-auto flex h-14 max-w-7xl items-center px-4 lg:px-6"><Link to="/pharmacy/orders" className="font-hero font-bold">Blissley <span className="font-normal text-ink/45">Pharmacy</span></Link><div className="ml-auto hidden text-xs text-ink/50 sm:block">{pharmacy}</div><Button variant="ghost" size="icon" className="ml-2" title="Sign out" onClick={()=>{platformActions.signOutPharmacy();nav({to:"/pharmacy/login"})}}><LogOut/></Button></div></header><div className="mx-auto flex max-w-7xl"><aside className="hidden min-h-[calc(100vh-56px)] w-48 shrink-0 border-r border-ink/10 bg-white p-3 md:block"><Link to="/pharmacy/orders" className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm ${path.startsWith("/pharmacy/orders")?"bg-marine/10 font-semibold text-marine":"text-ink/60"}`}><Package className="h-4 w-4"/>Orders</Link><Link to="/pharmacy/me" className={`mt-1 flex items-center gap-2 rounded-md px-3 py-2 text-sm ${path==="/pharmacy/me"?"bg-marine/10 font-semibold text-marine":"text-ink/60"}`}><UserRound className="h-4 w-4"/>Account</Link></aside><main className="min-w-0 flex-1 px-4 py-5 lg:px-7"><div className="mb-5 flex items-center justify-between"><h1 className="text-2xl font-semibold">{title}</h1><div className="flex gap-1 md:hidden"><Button asChild variant={path.startsWith("/pharmacy/orders")?"secondary":"ghost"} size="sm"><Link to="/pharmacy/orders">Orders</Link></Button><Button asChild variant={path==="/pharmacy/me"?"secondary":"ghost"} size="sm"><Link to="/pharmacy/me">Account</Link></Button></div></div>{children}</main></div></div>;
}