import { Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, ShieldCheck } from "lucide-react";
import { Button } from "@/components/ui/button";
import { platformActions } from "@/lib/platform/store";

export function PlatformLogin({ kind }: { kind:"operator"|"pharmacy" }) {
  const nav=useNavigate(); const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [error,setError]=useState("");const [loading,setLoading]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError("");setLoading(true);await new Promise(r=>setTimeout(r,450));if(!email.includes("@")||password.length<4){setError("Use a valid work email and a password of at least 4 characters.");setLoading(false);return}if(kind==="pharmacy"&&email.toLowerCase().includes("operator")){setError("This account does not have pharmacy access.");setLoading(false);return}kind==="operator"?platformActions.signInOperator(email):platformActions.signInPharmacy(email);setLoading(false);nav({to:kind==="operator"?"/operator":"/pharmacy/orders"})};
  return <main className="admin-scope grid min-h-screen place-items-center bg-canvas px-4"><div className="w-full max-w-sm"><Link to="/" className="font-hero text-xl font-bold text-ink">Blissley</Link><div className="mt-8 rounded-lg border border-ink/10 bg-white p-6 shadow-sm"><div className="flex items-center gap-2 text-xs font-semibold uppercase text-ink/45"><ShieldCheck className="h-4 w-4"/>{kind==="operator"?"Internal operations":"Pharmacy fulfillment"}</div><h1 className="mt-3 text-2xl font-semibold">Sign in</h1><p className="mt-1 text-sm text-ink/55">Use your authorized {kind} account.</p><form className="mt-6 space-y-4" onSubmit={submit}><label className="block text-sm font-medium">Work email<input className="mt-1.5 w-full rounded-md border border-input bg-background px-3 py-2.5 outline-none focus:ring-2 focus:ring-ring/30" type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder={kind==="operator"?"operator@blissley.com":"staff@southendpharmacy.com"}/></label><label className="block text-sm font-medium">Password<input className="mt-1.5 w-full rounded-md border border-input bg-background px-3 py-2.5 outline-none focus:ring-2 focus:ring-ring/30" type="password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div role="alert" className="rounded-md bg-ever/10 p-3 text-xs text-ever">{error}</div>}<Button className="w-full" disabled={loading}>{loading?"Signing in…":"Continue"}<ArrowRight/></Button></form></div><p className="mt-4 text-center text-xs text-ink/40">Demo access accepts any valid work email and 4+ character password.</p></div></main>
}