import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowRight, PackageCheck } from "lucide-react";
import { PharmacyShell } from "@/components/platform/PharmacyShell";
import { PlatformCard, StatusBadge } from "@/components/platform/OperatorShell";
import { Button } from "@/components/ui/button";
import { PHARMACY_NAMES, platformActions, type PharmacyOrderStatus, usePlatform } from "@/lib/platform/store";
const tabs:PharmacyOrderStatus[]=["pending","processing","shipped","delivered","failed"];
export const Route=createFileRoute("/pharmacy/orders/")({head:()=>({meta:[{title:"Prescription queue — Blissley Pharmacy"},{name:"description",content:"Process and track assigned prescription orders."},{property:"og:title",content:"Prescription queue — Blissley Pharmacy"},{property:"og:description",content:"Process and track assigned prescription orders."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"}]}),component:Orders});
function Orders(){const session=usePlatform(s=>s.pharmacySession),all=usePlatform(s=>s.orders),[tab,setTab]=useState<PharmacyOrderStatus>("pending");const pharmacyId=session?.pharmacyId??"southend";const mine=all.filter(o=>o.pharmacyId===pharmacyId),rows=mine.filter(o=>o.status===tab).sort((a,b)=>tab==="pending"?a.receivedAt-b.receivedAt:b.receivedAt-a.receivedAt);const stats=["pending","processing","shipped","failed"].map(k=>({k,v:mine.filter(o=>o.status===k&&(k!=="shipped"||Date.now()-(o.shippedAt??0)<86400000)).length}));return <PharmacyShell title="Prescription orders"><div className="mb-4 grid grid-cols-2 gap-3 lg:grid-cols-4">{stats.map(s=><PlatformCard key={s.k} className="p-4"><div className="text-xs capitalize text-ink/50">{s.k==="shipped"?"Shipped today":s.k}</div><div className="mt-2 text-2xl font-semibold tabular-nums">{s.v}</div></PlatformCard>)}</div><PlatformCard><div className="flex gap-1 overflow-x-auto border-b border-ink/10 p-2">{tabs.map(t=><Button key={t} variant={tab===t?"secondary":"ghost"} size="sm" className="capitalize" onClick={()=>setTab(t)}>{t}<span className="text-ink/40">{mine.filter(o=>o.status===t).length}</span></Button>)}</div>{rows.length===0?<div className="grid min-h-56 place-items-center text-center"><div><PackageCheck className="mx-auto h-8 w-8 text-check"/><div className="mt-2 font-medium">No {tab} orders</div><p className="text-xs text-ink/45">This queue is clear.</p></div></div>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-ink/[0.025] text-xs text-ink/45"><tr>{["Order","Received","Medication","State","Status","Action",""].map(h=><th className="px-4 py-2.5 font-medium" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(o=><tr key={o.id} className="border-t border-ink/[0.06]"><td className="px-4 py-3 font-semibold">{o.id}</td><td className="px-4 text-ink/60">{new Date(o.receivedAt).toLocaleString([], {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</td><td className="px-4">{o.molecule}<div className="text-xs text-ink/45">{o.dose}</div></td><td className="px-4">{o.state}</td><td className="px-4"><StatusBadge value={o.status}/></td><td className="px-4">{o.status==="pending"&&<Button size="sm" onClick={()=>platformActions.processOrder(o.id)}>Start processing</Button>}{o.status==="failed"&&<Button size="sm" onClick={()=>platformActions.retryOrder(o.id)}>Resubmit</Button>}</td><td className="px-4"><Button asChild variant="ghost" size="icon"><Link to="/pharmacy/orders/$orderId" params={{orderId:o.id}} aria-label={`View ${o.id}`}><ArrowRight/></Link></Button></td></tr>)}</tbody></table></div>}</PlatformCard><p className="mt-3 text-xs text-ink/40">Showing prescriptions assigned to {PHARMACY_NAMES[pharmacyId]} only. Patient identity is intentionally excluded.</p></PharmacyShell>}