/**
 * Real Loox reviews exported from the Unhinged One Shopify store.
 * Only reviews that came with a customer photo are kept — the photo carries
 * the section. Copy is verbatim; nothing here is fabricated.
 */
export type UOReview = {
  id: string;
  name: string;
  rating: number;
  headline: string;
  body: string;
  image: string;
  date: string;
  handle: string;
  verified: boolean;
};

export const UO_PHOTO_REVIEWS: UOReview[] = [
  {
    id: "biYJ1y9rH",
    name: "Sally F.",
    rating: 5,
    headline: "Absolutely love these!",
    body: "The T-shirts and jumpers are great quality, super comfortable and the prints are exactly as pictured. The sizing was spot on too. They were an absolute hit. Plenty of laughs, plenty of comments and, most importantly, completely accurate.",
    image: "https://images.loox.io/uploads/2026/8/16/qOf44vO7t.jpg",
    date: "2026-08-16",
    handle: "my-sister-and-i-talk-shit-about-you-sweatshirt",
    verified: true,
  },
  {
    id: "G4D-Pqdzj",
    name: "Tisha L.",
    rating: 5,
    headline: "Love this",
    body: "",
    image: "https://images.loox.io/uploads/2026/6/22/wjpxxEjzI.jpg",
    date: "2026-06-22",
    handle: "euthanize-me-mom-sweatshirt",
    verified: true,
  },
  {
    id: "kY2MhAcj5",
    name: "Tina M.",
    rating: 5,
    headline: "Fantastic",
    body: "",
    image: "https://images.loox.io/uploads/2026/4/5/msJEhWxKz.jpg",
    date: "2026-04-02",
    handle: "mom-didnt-raise-a-bitch-if-she-did-it-was-definitely-my-brother-unisex-classic-tee",
    verified: true,
  },
  {
    id: "m30Z6lQGy",
    name: "Stephanie W.",
    rating: 5,
    headline: "This is such a fun sibling shirt.",
    body: "I love that it\u2019s bold but still cute. Perfect for family gatherings.",
    image: "https://images.loox.io/uploads/2026/2/12/TeMpLiDAz.jpg",
    date: "2026-02-12",
    handle: "proud-sister-of-my-dumbass-brother-unisex-sweatshirt",
    verified: false,
  },
  {
    id: "cE-GYES2I",
    name: "Lauren P.",
    rating: 5,
    headline: "This is my new airport outfit.",
    body: "Comfortable, funny, and slightly aggressive in the best way. Got so many laughs.",
    image: "https://images.loox.io/uploads/2026/2/12/Ak55AdNrR.jpg",
    date: "2026-02-12",
    handle: "do-i-look-like-fucking-people-person-crewneck-sweatshirt",
    verified: false,
  },
  {
    id: "7YaMbzFdW",
    name: "Brianna S.",
    rating: 5,
    headline: "This sweatshirt is hilarious, I\u2019ve already had three people ask me where I got it. It\u2019s comfy, fits true to size, and the print quality is really good.",
    body: "",
    image: "https://images.loox.io/uploads/2026/2/12/0M8jBK5wS.jpg",
    date: "2026-02-12",
    handle: "my-mom-and-i-talk-shit-about-you-unisex-sweatshirt",
    verified: false,
  },
  {
    id: "zk1klNi9r",
    name: "Sarah L.",
    rating: 5,
    headline: "I love this Tee\u2764\ufe0f, i am going to wear this in family get together \ud83e\udd23...",
    body: "can't wait \ud83d\ude08",
    image: "https://images.loox.io/uploads/2026/2/12/Y5N5iTK-t.jpg",
    date: "2026-02-12",
    handle: "acting-like-my-mom-t-shirt",
    verified: false,
  },
  {
    id: "TngLaN-W_",
    name: "Brandi R.",
    rating: 5,
    headline: "I love this shirt\ud83e\udd70, absolutey converstation starter \ud83d\udd25",
    body: "",
    image: "https://images.loox.io/uploads/2026/2/12/vMclPiyPDh.jpg",
    date: "2026-02-12",
    handle: "my-sister-and-i-talk-shit-about-you-sweatshirt",
    verified: false,
  },
  {
    id: "qEiJWqcok",
    name: "Susan  L.",
    rating: 5,
    headline: "I Gift this shirt to my mom and she loved\u2764\ufe0f it so much.",
    body: "Where ever we go she wear this shirt every time\ud83d\ude2d\ud83e\udd23\ud83d\ude1c...",
    image: "https://images.loox.io/uploads/2026/2/12/RQwMScZqk.jpg",
    date: "2026-02-12",
    handle: "my-daughter-and-i-talk-shit-about-you-unisex-sweatshirt",
    verified: false,
  },
  {
    id: "WtGH4asFq",
    name: "Maria  D.",
    rating: 5,
    headline: "i really loved this shirt, first thing this is so funny directly resonate with our sibling bonding\ud83e\udd23. it came so quickly and when it arived i wore it and we laughed like crazy. and shirt material is good and it feels comfy. i'll order again\u2764\ufe0f\u270c\ud83c\udffb",
    body: "",
    image: "https://images.loox.io/uploads/2026/2/12/BlNuw1o6F.jpg",
    date: "2026-02-12",
    handle: "proud-sister-of-my-dumbass-brother-unisex-sweatshirt",
    verified: false,
  },
  {
    id: "S-yRXhb1j9",
    name: "Ashley R.",
    rating: 5,
    headline: "wore this to get coffee and the barista read it slowly and said wait is fluoxetine the one that. YES. it is the one that. you don't even have to finish the sentence. we all know which one it is",
    body: "",
    image: "https://images.loox.io/uploads/2026/3/5/6UwMyiimx.jpg",
    date: "2026-01-22",
    handle: "may-be-shes-born-with-it-fluoxetine-sweatshirt",
    verified: true,
  },
  {
    id: "ejnIUTDS4",
    name: "Michelle S.",
    rating: 5,
    headline: "My favorite sweatshirt!",
    body: "Excellent quality, soft and comfortable. And who doesn\u2019t love a good laugh?!",
    image: "https://images.loox.io/uploads/2026/1/1/HsD0T1G42.jpg",
    date: "2026-01-01",
    handle: "let-me-guess-sweatshirt",
    verified: true,
  },
  {
    id: "bFqy-3K8H",
    name: "Christine P.",
    rating: 5,
    headline: "It's comfortable i guess,  like the fabric and it's not irritating for my sensitive skin.",
    body: "",
    image: "https://images.loox.io/uploads/2025/12/7/LAKBbwAvi.jpg",
    date: "2025-12-07",
    handle: "dont-make-me-angry-or-ill-start-acting-as-my-mother-crewneck-sweatshirt",
    verified: true,
  },
  {
    id: "Ctc1LH5QI",
    name: "Wendy S.",
    rating: 5,
    headline: "Such a great product.",
    body: "The material is comfortable and breathable but does keep me warm. I have gotten compliments on people who love the shirt. Definitely a conversation starter. My brother even loved it.",
    image: "https://images.loox.io/uploads/2025/11/16/Zren8hj1w.jpg",
    date: "2025-11-16",
    handle: "proud-sister-of-my-dumbass-brothertm-hooded-sweatshirt",
    verified: true,
  },
  {
    id: "wTvtofC2gl",
    name: "Megan T.",
    rating: 5,
    headline: "the pharmacist handed me my prescription and read my shirt at the same time and just started laughing. she said girl you are the third person this month wearing something about their meds. we are all coming out. medicated and proud",
    body: "",
    image: "https://images.loox.io/uploads/2026/3/5/uZULZXlnBq.jpg",
    date: "2025-11-14",
    handle: "may-be-shes-born-with-it-fluoxetine-sweatshirt",
    verified: true,
  },
  {
    id: "3BKoLDmIH",
    name: "Rebecca H.",
    rating: 5,
    headline: "The sweatshirt is awesome.",
    body: "Customer service was wonderful!!",
    image: "https://images.loox.io/uploads/2025/9/17/pfw9Aj3Mw.jpg",
    date: "2025-09-17",
    handle: "tell-my-dad-sweatshirt",
    verified: true,
  },
  {
    id: "wF_KpwFjq",
    name: "Jamie F.",
    rating: 5,
    headline: "My mom saw this sweatshirt on facebook and sent it to me.",
    body: "I said, \"That's so funny, if it were baby pink I'd get it\". Then I looked, and it does in fact come in pink, so I bought it. It shipped fast and is so soft and comfortable (I got an XL for it to be oversized). It is definitely a conversation starter, A.K.A everybody wants to know my lore. Anyways I'm super happy with my purchase :)",
    image: "https://images.loox.io/uploads/2025/8/7/9LO8M-av0.jpg",
    date: "2025-08-07",
    handle: "my-dads-alive-just-dead-to-me-crewneck-sweatshirt",
    verified: true,
  },
  {
    id: "_sdMLJsFP",
    name: "Brenna C.",
    rating: 3,
    headline: "Comfy sweatshirt, got here quickly!",
    body: "Rating 3 stars instead of 5 because the font is NOT what is pictured/what I ordered. I personally do not want to go through the hassle of returning, but I\u2019m very disappointed that it came with a different font that I like much less that what was shown on the site.",
    image: "https://images.loox.io/uploads/2025/7/19/ru33mp89S8.jpg",
    date: "2025-07-19",
    handle: "my-dads-alive-just-dead-to-me-crewneck-sweatshirt",
    verified: false,
  },
  {
    id: "2n3IAfVZv",
    name: "Harriet  R.",
    rating: 5,
    headline: "My mom really loved this shirt, shipping was fast, quality is really great for the price of the shirt.",
    body: "",
    image: "https://images.loox.io/uploads/2025/3/15/3cGBlHAV8.jpg",
    date: "2025-03-15",
    handle: "my-daughter-and-i-talk-shit-about-you-unisex-sweatshirt",
    verified: false,
  },
  {
    id: "MV9GN76fv",
    name: "Traci H.",
    rating: 5,
    headline: "We wore this on a Sunday to dinner and we made my mom laugh so hard.",
    body: "The sweater is very comfy and cozy. Would wear it everyday if I could.",
    image: "https://images.loox.io/uploads/2025/3/11/F2DiTfUKg-.jpg",
    date: "2025-03-11",
    handle: "dont-make-me-angry-or-ill-start-acting-as-my-mother-crewneck-sweatshirt",
    verified: true,
  },
  {
    id: "RghTwE4_e",
    name: "SERENE M.",
    rating: 5,
    headline: "I absolutely love this sweater!",
    body: "I wear it to every single doctors appointments that I go to to remind my doctors to actually listen to what I'm saying. So far, I've had SO many nurses compliment me on it and tell me how much they love my bravery for wearing it to the doctors office. It's so cozy too, so that's just a great bonus!",
    image: "https://images.loox.io/uploads/2025/1/25/964rherXa.jpg",
    date: "2025-01-25",
    handle: "let-me-guess-sweatshirt",
    verified: true,
  },
  {
    id: "5zDmbt2nE",
    name: "Janelle S.",
    rating: 5,
    headline: "My kids love them!!",
    body: "",
    image: "https://images.loox.io/uploads/2025/1/5/WxD-3oPYR.jpg",
    date: "2025-01-05",
    handle: "my-sister-and-i-talk-shit-about-you-sweatshirt",
    verified: true,
  },
  {
    id: "hmZANYVG2",
    name: "Julianne A.",
    rating: 5,
    headline: "Wore this on Thanksgiving.",
    body: "It was hilarious \ud83d\ude02",
    image: "https://images.loox.io/uploads/2024/12/1/UIN3co8cm.jpg",
    date: "2024-12-01",
    handle: "my-sister-and-i-talk-shit-about-you-sweatshirt",
    verified: true,
  },
  {
    id: "6T3sAd9e5",
    name: "Michelle B.",
    rating: 5,
    headline: "This sweatshirt is perfect! Super comfy and gets laughs every time I wear it.",
    body: "When my brother saw it , his face was priceless\ud83d\ude02 , can\u2019t wait to wear it for Thanksgiving.",
    image: "https://images.loox.io/uploads/2024/11/3/AlPqQR_Cb.jpg",
    date: "2024-11-03",
    handle: "proud-sister-of-my-dumbass-brother-sweatshirt",
    verified: false,
  },
];
