/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestStateRouteImport } from './routes/test-state'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MedicationSafetyRouteImport } from './routes/medication-safety'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as ConfirmationChargedRouteImport } from './routes/confirmation-charged'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeightLossIndexRouteImport } from './routes/weight-loss.index'
import { Route as OperatorIndexRouteImport } from './routes/operator.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WeightLossSalesRouteImport } from './routes/weight-loss.sales'
import { Route as SalesTrimrxRouteImport } from './routes/sales.trimrx'
import { Route as SalesDMRouteImport } from './routes/sales.DM'
import { Route as PortalPhysicianRouteImport } from './routes/portal.physician'
import { Route as PortalPatientRouteImport } from './routes/portal.patient'
import { Route as PharmacyMeRouteImport } from './routes/pharmacy.me'
import { Route as PharmacyLoginRouteImport } from './routes/pharmacy.login'
import { Route as OperatorLoginRouteImport } from './routes/operator.login'
import { Route as OperatorDashboardRouteImport } from './routes/operator.dashboard'
import { Route as LoginPhysicianRouteImport } from './routes/login.physician'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as IntakeWeightloss3RouteImport } from './routes/intake_.weightloss-3'
import { Route as IntakeWeightLossTrimrx2RouteImport } from './routes/intake_.weight-loss-trimrx-2'
import { Route as IntakeWeightLossTrimrxRouteImport } from './routes/intake_.weight-loss-trimrx'
import { Route as IntakeWeightLossRouteImport } from './routes/intake_.weight-loss'
import { Route as IntakeNewWeightlossOursRouteImport } from './routes/intake_.new-weightloss-ours'
import { Route as CheckoutTrimrxRouteImport } from './routes/checkout.trimrx'
import { Route as CheckoutChargedBeforeRouteImport } from './routes/checkout.charged-before'
import { Route as CheckoutUITemplate3RouteImport } from './routes/checkout.UI-template3'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPharmacyRouteImport } from './routes/admin.pharmacy'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminCommandRouteImport } from './routes/admin.command'
import { Route as PharmacyOrdersIndexRouteImport } from './routes/pharmacy.orders.index'
import { Route as AdminSettingsIndexRouteImport } from './routes/admin.settings.index'
import { Route as AdminPhysicianQueueIndexRouteImport } from './routes/admin.physician-queue.index'
import { Route as AdminPatientsIndexRouteImport } from './routes/admin.patients.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminLeadsIndexRouteImport } from './routes/admin.leads.index'
import { Route as AdminIntegrationsIndexRouteImport } from './routes/admin.integrations.index'
import { Route as AdminCheckInsIndexRouteImport } from './routes/admin.check-ins.index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin.analytics.index'
import { Route as AdminSettingsTeamRouteImport } from './routes/admin.settings.team'
import { Route as AdminSettingsStatesRouteImport } from './routes/admin.settings.states'
import { Route as AdminSettingsPlanBillingRouteImport } from './routes/admin.settings.plan-billing'
import { Route as AdminSettingsPharmacyRoutingRouteImport } from './routes/admin.settings.pharmacy-routing'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/admin.settings.notifications'
import { Route as AdminSettingsLegalRouteImport } from './routes/admin.settings.legal'
import { Route as AdminSettingsIntegrationsRouteImport } from './routes/admin.settings.integrations'
import { Route as AdminSettingsGeneralRouteImport } from './routes/admin.settings.general'
import { Route as AdminSettingsComplianceRouteImport } from './routes/admin.settings.compliance'
import { Route as AdminPhysicianQueueIdRouteImport } from './routes/admin.physician-queue.$id'
import { Route as AdminPatientsIdRouteImport } from './routes/admin.patients.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminLeadsIdRouteImport } from './routes/admin.leads.$id'
import { Route as AdminIntegrationsIdRouteImport } from './routes/admin.integrations.$id'
import { Route as AdminCheckInsIdRouteImport } from './routes/admin.check-ins.$id'
import { Route as AdminBuildProductsRouteImport } from './routes/admin.build.products'
import { Route as AdminBuildPagesRouteImport } from './routes/admin.build.pages'
import { Route as AdminBuildIntakeRouteImport } from './routes/admin.build.intake'
import { Route as AdminBuildFunnelRouteImport } from './routes/admin.build.funnel'
import { Route as AdminBuildEmailsRouteImport } from './routes/admin.build.emails'
import { Route as AdminAnalyticsRetentionRouteImport } from './routes/admin.analytics.retention'
import { Route as AdminAnalyticsFunnelRouteImport } from './routes/admin.analytics.funnel'
import { Route as AdminAnalyticsFinancesRouteImport } from './routes/admin.analytics.finances'
import { Route as AdminAnalyticsAcquisitionRouteImport } from './routes/admin.analytics.acquisition'

const TestStateRoute = TestStateRouteImport.update({
  id: '/test-state',
  path: '/test-state',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationSafetyRoute = MedicationSafetyRouteImport.update({
  id: '/medication-safety',
  path: '/medication-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationChargedRoute = ConfirmationChargedRouteImport.update({
  id: '/confirmation-charged',
  path: '/confirmation-charged',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightLossIndexRoute = WeightLossIndexRouteImport.update({
  id: '/weight-loss/',
  path: '/weight-loss/',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorIndexRoute = OperatorIndexRouteImport.update({
  id: '/operator/',
  path: '/operator/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightLossSalesRoute = WeightLossSalesRouteImport.update({
  id: '/weight-loss/sales',
  path: '/weight-loss/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTrimrxRoute = SalesTrimrxRouteImport.update({
  id: '/sales/trimrx',
  path: '/sales/trimrx',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDMRoute = SalesDMRouteImport.update({
  id: '/sales/DM',
  path: '/sales/DM',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPhysicianRoute = PortalPhysicianRouteImport.update({
  id: '/portal/physician',
  path: '/portal/physician',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPatientRoute = PortalPatientRouteImport.update({
  id: '/portal/patient',
  path: '/portal/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyMeRoute = PharmacyMeRouteImport.update({
  id: '/pharmacy/me',
  path: '/pharmacy/me',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyLoginRoute = PharmacyLoginRouteImport.update({
  id: '/pharmacy/login',
  path: '/pharmacy/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorLoginRoute = OperatorLoginRouteImport.update({
  id: '/operator/login',
  path: '/operator/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorDashboardRoute = OperatorDashboardRouteImport.update({
  id: '/operator/dashboard',
  path: '/operator/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPhysicianRoute = LoginPhysicianRouteImport.update({
  id: '/physician',
  path: '/physician',
  getParentRoute: () => LoginRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LoginRoute,
} as any)
const IntakeWeightloss3Route = IntakeWeightloss3RouteImport.update({
  id: '/intake_/weightloss-3',
  path: '/intake/weightloss-3',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeWeightLossTrimrx2Route = IntakeWeightLossTrimrx2RouteImport.update({
  id: '/intake_/weight-loss-trimrx-2',
  path: '/intake/weight-loss-trimrx-2',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeWeightLossTrimrxRoute = IntakeWeightLossTrimrxRouteImport.update({
  id: '/intake_/weight-loss-trimrx',
  path: '/intake/weight-loss-trimrx',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeWeightLossRoute = IntakeWeightLossRouteImport.update({
  id: '/intake_/weight-loss',
  path: '/intake/weight-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeNewWeightlossOursRoute = IntakeNewWeightlossOursRouteImport.update({
  id: '/intake_/new-weightloss-ours',
  path: '/intake/new-weightloss-ours',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTrimrxRoute = CheckoutTrimrxRouteImport.update({
  id: '/checkout/trimrx',
  path: '/checkout/trimrx',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutChargedBeforeRoute = CheckoutChargedBeforeRouteImport.update({
  id: '/checkout/charged-before',
  path: '/checkout/charged-before',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutUITemplate3Route = CheckoutUITemplate3RouteImport.update({
  id: '/checkout/UI-template3',
  path: '/checkout/UI-template3',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPharmacyRoute = AdminPharmacyRouteImport.update({
  id: '/admin/pharmacy',
  path: '/admin/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/admin/live',
  path: '/admin/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandRoute = AdminCommandRouteImport.update({
  id: '/admin/command',
  path: '/admin/command',
  getParentRoute: () => rootRouteImport,
} as any)
const PharmacyOrdersIndexRoute = PharmacyOrdersIndexRouteImport.update({
  id: '/pharmacy/orders/',
  path: '/pharmacy/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsIndexRoute = AdminSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminPhysicianQueueIndexRoute =
  AdminPhysicianQueueIndexRouteImport.update({
    id: '/admin/physician-queue/',
    path: '/admin/physician-queue/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminPatientsIndexRoute = AdminPatientsIndexRouteImport.update({
  id: '/admin/patients/',
  path: '/admin/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/admin/leads/',
  path: '/admin/leads/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsIndexRoute = AdminIntegrationsIndexRouteImport.update({
  id: '/admin/integrations/',
  path: '/admin/integrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckInsIndexRoute = AdminCheckInsIndexRouteImport.update({
  id: '/admin/check-ins/',
  path: '/admin/check-ins/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/admin/analytics/',
  path: '/admin/analytics/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsTeamRoute = AdminSettingsTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsStatesRoute = AdminSettingsStatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsPlanBillingRoute =
  AdminSettingsPlanBillingRouteImport.update({
    id: '/plan-billing',
    path: '/plan-billing',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsPharmacyRoutingRoute =
  AdminSettingsPharmacyRoutingRouteImport.update({
    id: '/pharmacy-routing',
    path: '/pharmacy-routing',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsLegalRoute = AdminSettingsLegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsIntegrationsRoute =
  AdminSettingsIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AdminSettingsRoute,
  } as any)
const AdminSettingsGeneralRoute = AdminSettingsGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminSettingsComplianceRoute = AdminSettingsComplianceRouteImport.update({
  id: '/compliance',
  path: '/compliance',
  getParentRoute: () => AdminSettingsRoute,
} as any)
const AdminPhysicianQueueIdRoute = AdminPhysicianQueueIdRouteImport.update({
  id: '/admin/physician-queue/$id',
  path: '/admin/physician-queue/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/admin/patients/$id',
  path: '/admin/patients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/admin/orders/$id',
  path: '/admin/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsIdRoute = AdminLeadsIdRouteImport.update({
  id: '/admin/leads/$id',
  path: '/admin/leads/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsIdRoute = AdminIntegrationsIdRouteImport.update({
  id: '/admin/integrations/$id',
  path: '/admin/integrations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckInsIdRoute = AdminCheckInsIdRouteImport.update({
  id: '/admin/check-ins/$id',
  path: '/admin/check-ins/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuildProductsRoute = AdminBuildProductsRouteImport.update({
  id: '/admin/build/products',
  path: '/admin/build/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuildPagesRoute = AdminBuildPagesRouteImport.update({
  id: '/admin/build/pages',
  path: '/admin/build/pages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuildIntakeRoute = AdminBuildIntakeRouteImport.update({
  id: '/admin/build/intake',
  path: '/admin/build/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuildFunnelRoute = AdminBuildFunnelRouteImport.update({
  id: '/admin/build/funnel',
  path: '/admin/build/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBuildEmailsRoute = AdminBuildEmailsRouteImport.update({
  id: '/admin/build/emails',
  path: '/admin/build/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRetentionRoute = AdminAnalyticsRetentionRouteImport.update({
  id: '/admin/analytics/retention',
  path: '/admin/analytics/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsFunnelRoute = AdminAnalyticsFunnelRouteImport.update({
  id: '/admin/analytics/funnel',
  path: '/admin/analytics/funnel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsFinancesRoute = AdminAnalyticsFinancesRouteImport.update({
  id: '/admin/analytics/finances',
  path: '/admin/analytics/finances',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsAcquisitionRoute =
  AdminAnalyticsAcquisitionRouteImport.update({
    id: '/admin/analytics/acquisition',
    path: '/admin/analytics/acquisition',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/confirmation-charged': typeof ConfirmationChargedRoute
  '/emails': typeof EmailsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRouteWithChildren
  '/medication-safety': typeof MedicationSafetyRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/test-state': typeof TestStateRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/team': typeof AdminTeamRoute
  '/checkout/UI-template3': typeof CheckoutUITemplate3Route
  '/checkout/charged-before': typeof CheckoutChargedBeforeRoute
  '/checkout/trimrx': typeof CheckoutTrimrxRoute
  '/intake/new-weightloss-ours': typeof IntakeNewWeightlossOursRoute
  '/intake/weight-loss': typeof IntakeWeightLossRoute
  '/intake/weight-loss-trimrx': typeof IntakeWeightLossTrimrxRoute
  '/intake/weight-loss-trimrx-2': typeof IntakeWeightLossTrimrx2Route
  '/intake/weightloss-3': typeof IntakeWeightloss3Route
  '/login/admin': typeof LoginAdminRoute
  '/login/physician': typeof LoginPhysicianRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/login': typeof OperatorLoginRoute
  '/pharmacy/login': typeof PharmacyLoginRoute
  '/pharmacy/me': typeof PharmacyMeRoute
  '/portal/patient': typeof PortalPatientRoute
  '/portal/physician': typeof PortalPhysicianRoute
  '/sales/DM': typeof SalesDMRoute
  '/sales/trimrx': typeof SalesTrimrxRoute
  '/weight-loss/sales': typeof WeightLossSalesRoute
  '/admin/': typeof AdminIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/weight-loss/': typeof WeightLossIndexRoute
  '/admin/analytics/acquisition': typeof AdminAnalyticsAcquisitionRoute
  '/admin/analytics/finances': typeof AdminAnalyticsFinancesRoute
  '/admin/analytics/funnel': typeof AdminAnalyticsFunnelRoute
  '/admin/analytics/retention': typeof AdminAnalyticsRetentionRoute
  '/admin/build/emails': typeof AdminBuildEmailsRoute
  '/admin/build/funnel': typeof AdminBuildFunnelRoute
  '/admin/build/intake': typeof AdminBuildIntakeRoute
  '/admin/build/pages': typeof AdminBuildPagesRoute
  '/admin/build/products': typeof AdminBuildProductsRoute
  '/admin/check-ins/$id': typeof AdminCheckInsIdRoute
  '/admin/integrations/$id': typeof AdminIntegrationsIdRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/physician-queue/$id': typeof AdminPhysicianQueueIdRoute
  '/admin/settings/compliance': typeof AdminSettingsComplianceRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/legal': typeof AdminSettingsLegalRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/pharmacy-routing': typeof AdminSettingsPharmacyRoutingRoute
  '/admin/settings/plan-billing': typeof AdminSettingsPlanBillingRoute
  '/admin/settings/states': typeof AdminSettingsStatesRoute
  '/admin/settings/team': typeof AdminSettingsTeamRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/check-ins/': typeof AdminCheckInsIndexRoute
  '/admin/integrations/': typeof AdminIntegrationsIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/physician-queue/': typeof AdminPhysicianQueueIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/pharmacy/orders/': typeof PharmacyOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/confirmation-charged': typeof ConfirmationChargedRoute
  '/emails': typeof EmailsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRouteWithChildren
  '/medication-safety': typeof MedicationSafetyRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/test-state': typeof TestStateRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/team': typeof AdminTeamRoute
  '/checkout/UI-template3': typeof CheckoutUITemplate3Route
  '/checkout/charged-before': typeof CheckoutChargedBeforeRoute
  '/checkout/trimrx': typeof CheckoutTrimrxRoute
  '/intake/new-weightloss-ours': typeof IntakeNewWeightlossOursRoute
  '/intake/weight-loss': typeof IntakeWeightLossRoute
  '/intake/weight-loss-trimrx': typeof IntakeWeightLossTrimrxRoute
  '/intake/weight-loss-trimrx-2': typeof IntakeWeightLossTrimrx2Route
  '/intake/weightloss-3': typeof IntakeWeightloss3Route
  '/login/admin': typeof LoginAdminRoute
  '/login/physician': typeof LoginPhysicianRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/login': typeof OperatorLoginRoute
  '/pharmacy/login': typeof PharmacyLoginRoute
  '/pharmacy/me': typeof PharmacyMeRoute
  '/portal/patient': typeof PortalPatientRoute
  '/portal/physician': typeof PortalPhysicianRoute
  '/sales/DM': typeof SalesDMRoute
  '/sales/trimrx': typeof SalesTrimrxRoute
  '/weight-loss/sales': typeof WeightLossSalesRoute
  '/admin': typeof AdminIndexRoute
  '/operator': typeof OperatorIndexRoute
  '/weight-loss': typeof WeightLossIndexRoute
  '/admin/analytics/acquisition': typeof AdminAnalyticsAcquisitionRoute
  '/admin/analytics/finances': typeof AdminAnalyticsFinancesRoute
  '/admin/analytics/funnel': typeof AdminAnalyticsFunnelRoute
  '/admin/analytics/retention': typeof AdminAnalyticsRetentionRoute
  '/admin/build/emails': typeof AdminBuildEmailsRoute
  '/admin/build/funnel': typeof AdminBuildFunnelRoute
  '/admin/build/intake': typeof AdminBuildIntakeRoute
  '/admin/build/pages': typeof AdminBuildPagesRoute
  '/admin/build/products': typeof AdminBuildProductsRoute
  '/admin/check-ins/$id': typeof AdminCheckInsIdRoute
  '/admin/integrations/$id': typeof AdminIntegrationsIdRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/physician-queue/$id': typeof AdminPhysicianQueueIdRoute
  '/admin/settings/compliance': typeof AdminSettingsComplianceRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/legal': typeof AdminSettingsLegalRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/pharmacy-routing': typeof AdminSettingsPharmacyRoutingRoute
  '/admin/settings/plan-billing': typeof AdminSettingsPlanBillingRoute
  '/admin/settings/states': typeof AdminSettingsStatesRoute
  '/admin/settings/team': typeof AdminSettingsTeamRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/check-ins': typeof AdminCheckInsIndexRoute
  '/admin/integrations': typeof AdminIntegrationsIndexRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/patients': typeof AdminPatientsIndexRoute
  '/admin/physician-queue': typeof AdminPhysicianQueueIndexRoute
  '/admin/settings': typeof AdminSettingsIndexRoute
  '/pharmacy/orders': typeof PharmacyOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/confirmation-charged': typeof ConfirmationChargedRoute
  '/emails': typeof EmailsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRouteWithChildren
  '/medication-safety': typeof MedicationSafetyRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/test-state': typeof TestStateRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRouteWithChildren
  '/admin/team': typeof AdminTeamRoute
  '/checkout/UI-template3': typeof CheckoutUITemplate3Route
  '/checkout/charged-before': typeof CheckoutChargedBeforeRoute
  '/checkout/trimrx': typeof CheckoutTrimrxRoute
  '/intake_/new-weightloss-ours': typeof IntakeNewWeightlossOursRoute
  '/intake_/weight-loss': typeof IntakeWeightLossRoute
  '/intake_/weight-loss-trimrx': typeof IntakeWeightLossTrimrxRoute
  '/intake_/weight-loss-trimrx-2': typeof IntakeWeightLossTrimrx2Route
  '/intake_/weightloss-3': typeof IntakeWeightloss3Route
  '/login/admin': typeof LoginAdminRoute
  '/login/physician': typeof LoginPhysicianRoute
  '/operator/dashboard': typeof OperatorDashboardRoute
  '/operator/login': typeof OperatorLoginRoute
  '/pharmacy/login': typeof PharmacyLoginRoute
  '/pharmacy/me': typeof PharmacyMeRoute
  '/portal/patient': typeof PortalPatientRoute
  '/portal/physician': typeof PortalPhysicianRoute
  '/sales/DM': typeof SalesDMRoute
  '/sales/trimrx': typeof SalesTrimrxRoute
  '/weight-loss/sales': typeof WeightLossSalesRoute
  '/admin/': typeof AdminIndexRoute
  '/operator/': typeof OperatorIndexRoute
  '/weight-loss/': typeof WeightLossIndexRoute
  '/admin/analytics/acquisition': typeof AdminAnalyticsAcquisitionRoute
  '/admin/analytics/finances': typeof AdminAnalyticsFinancesRoute
  '/admin/analytics/funnel': typeof AdminAnalyticsFunnelRoute
  '/admin/analytics/retention': typeof AdminAnalyticsRetentionRoute
  '/admin/build/emails': typeof AdminBuildEmailsRoute
  '/admin/build/funnel': typeof AdminBuildFunnelRoute
  '/admin/build/intake': typeof AdminBuildIntakeRoute
  '/admin/build/pages': typeof AdminBuildPagesRoute
  '/admin/build/products': typeof AdminBuildProductsRoute
  '/admin/check-ins/$id': typeof AdminCheckInsIdRoute
  '/admin/integrations/$id': typeof AdminIntegrationsIdRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
  '/admin/physician-queue/$id': typeof AdminPhysicianQueueIdRoute
  '/admin/settings/compliance': typeof AdminSettingsComplianceRoute
  '/admin/settings/general': typeof AdminSettingsGeneralRoute
  '/admin/settings/integrations': typeof AdminSettingsIntegrationsRoute
  '/admin/settings/legal': typeof AdminSettingsLegalRoute
  '/admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/admin/settings/pharmacy-routing': typeof AdminSettingsPharmacyRoutingRoute
  '/admin/settings/plan-billing': typeof AdminSettingsPlanBillingRoute
  '/admin/settings/states': typeof AdminSettingsStatesRoute
  '/admin/settings/team': typeof AdminSettingsTeamRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/check-ins/': typeof AdminCheckInsIndexRoute
  '/admin/integrations/': typeof AdminIntegrationsIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/patients/': typeof AdminPatientsIndexRoute
  '/admin/physician-queue/': typeof AdminPhysicianQueueIndexRoute
  '/admin/settings/': typeof AdminSettingsIndexRoute
  '/pharmacy/orders/': typeof PharmacyOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmation'
    | '/confirmation-charged'
    | '/emails'
    | '/intake'
    | '/login'
    | '/medication-safety'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/terms'
    | '/test-state'
    | '/admin/command'
    | '/admin/live'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/pharmacy'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/team'
    | '/checkout/UI-template3'
    | '/checkout/charged-before'
    | '/checkout/trimrx'
    | '/intake/new-weightloss-ours'
    | '/intake/weight-loss'
    | '/intake/weight-loss-trimrx'
    | '/intake/weight-loss-trimrx-2'
    | '/intake/weightloss-3'
    | '/login/admin'
    | '/login/physician'
    | '/operator/dashboard'
    | '/operator/login'
    | '/pharmacy/login'
    | '/pharmacy/me'
    | '/portal/patient'
    | '/portal/physician'
    | '/sales/DM'
    | '/sales/trimrx'
    | '/weight-loss/sales'
    | '/admin/'
    | '/operator/'
    | '/weight-loss/'
    | '/admin/analytics/acquisition'
    | '/admin/analytics/finances'
    | '/admin/analytics/funnel'
    | '/admin/analytics/retention'
    | '/admin/build/emails'
    | '/admin/build/funnel'
    | '/admin/build/intake'
    | '/admin/build/pages'
    | '/admin/build/products'
    | '/admin/check-ins/$id'
    | '/admin/integrations/$id'
    | '/admin/leads/$id'
    | '/admin/orders/$id'
    | '/admin/patients/$id'
    | '/admin/physician-queue/$id'
    | '/admin/settings/compliance'
    | '/admin/settings/general'
    | '/admin/settings/integrations'
    | '/admin/settings/legal'
    | '/admin/settings/notifications'
    | '/admin/settings/pharmacy-routing'
    | '/admin/settings/plan-billing'
    | '/admin/settings/states'
    | '/admin/settings/team'
    | '/admin/analytics/'
    | '/admin/check-ins/'
    | '/admin/integrations/'
    | '/admin/leads/'
    | '/admin/orders/'
    | '/admin/patients/'
    | '/admin/physician-queue/'
    | '/admin/settings/'
    | '/pharmacy/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmation'
    | '/confirmation-charged'
    | '/emails'
    | '/intake'
    | '/login'
    | '/medication-safety'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/terms'
    | '/test-state'
    | '/admin/command'
    | '/admin/live'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/pharmacy'
    | '/admin/reports'
    | '/admin/team'
    | '/checkout/UI-template3'
    | '/checkout/charged-before'
    | '/checkout/trimrx'
    | '/intake/new-weightloss-ours'
    | '/intake/weight-loss'
    | '/intake/weight-loss-trimrx'
    | '/intake/weight-loss-trimrx-2'
    | '/intake/weightloss-3'
    | '/login/admin'
    | '/login/physician'
    | '/operator/dashboard'
    | '/operator/login'
    | '/pharmacy/login'
    | '/pharmacy/me'
    | '/portal/patient'
    | '/portal/physician'
    | '/sales/DM'
    | '/sales/trimrx'
    | '/weight-loss/sales'
    | '/admin'
    | '/operator'
    | '/weight-loss'
    | '/admin/analytics/acquisition'
    | '/admin/analytics/finances'
    | '/admin/analytics/funnel'
    | '/admin/analytics/retention'
    | '/admin/build/emails'
    | '/admin/build/funnel'
    | '/admin/build/intake'
    | '/admin/build/pages'
    | '/admin/build/products'
    | '/admin/check-ins/$id'
    | '/admin/integrations/$id'
    | '/admin/leads/$id'
    | '/admin/orders/$id'
    | '/admin/patients/$id'
    | '/admin/physician-queue/$id'
    | '/admin/settings/compliance'
    | '/admin/settings/general'
    | '/admin/settings/integrations'
    | '/admin/settings/legal'
    | '/admin/settings/notifications'
    | '/admin/settings/pharmacy-routing'
    | '/admin/settings/plan-billing'
    | '/admin/settings/states'
    | '/admin/settings/team'
    | '/admin/analytics'
    | '/admin/check-ins'
    | '/admin/integrations'
    | '/admin/leads'
    | '/admin/orders'
    | '/admin/patients'
    | '/admin/physician-queue'
    | '/admin/settings'
    | '/pharmacy/orders'
  id:
    | '__root__'
    | '/'
    | '/confirmation'
    | '/confirmation-charged'
    | '/emails'
    | '/intake'
    | '/login'
    | '/medication-safety'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/terms'
    | '/test-state'
    | '/admin/command'
    | '/admin/live'
    | '/admin/messages'
    | '/admin/payments'
    | '/admin/pharmacy'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/team'
    | '/checkout/UI-template3'
    | '/checkout/charged-before'
    | '/checkout/trimrx'
    | '/intake_/new-weightloss-ours'
    | '/intake_/weight-loss'
    | '/intake_/weight-loss-trimrx'
    | '/intake_/weight-loss-trimrx-2'
    | '/intake_/weightloss-3'
    | '/login/admin'
    | '/login/physician'
    | '/operator/dashboard'
    | '/operator/login'
    | '/pharmacy/login'
    | '/pharmacy/me'
    | '/portal/patient'
    | '/portal/physician'
    | '/sales/DM'
    | '/sales/trimrx'
    | '/weight-loss/sales'
    | '/admin/'
    | '/operator/'
    | '/weight-loss/'
    | '/admin/analytics/acquisition'
    | '/admin/analytics/finances'
    | '/admin/analytics/funnel'
    | '/admin/analytics/retention'
    | '/admin/build/emails'
    | '/admin/build/funnel'
    | '/admin/build/intake'
    | '/admin/build/pages'
    | '/admin/build/products'
    | '/admin/check-ins/$id'
    | '/admin/integrations/$id'
    | '/admin/leads/$id'
    | '/admin/orders/$id'
    | '/admin/patients/$id'
    | '/admin/physician-queue/$id'
    | '/admin/settings/compliance'
    | '/admin/settings/general'
    | '/admin/settings/integrations'
    | '/admin/settings/legal'
    | '/admin/settings/notifications'
    | '/admin/settings/pharmacy-routing'
    | '/admin/settings/plan-billing'
    | '/admin/settings/states'
    | '/admin/settings/team'
    | '/admin/analytics/'
    | '/admin/check-ins/'
    | '/admin/integrations/'
    | '/admin/leads/'
    | '/admin/orders/'
    | '/admin/patients/'
    | '/admin/physician-queue/'
    | '/admin/settings/'
    | '/pharmacy/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ConfirmationChargedRoute: typeof ConfirmationChargedRoute
  EmailsRoute: typeof EmailsRoute
  IntakeRoute: typeof IntakeRoute
  LoginRoute: typeof LoginRouteWithChildren
  MedicationSafetyRoute: typeof MedicationSafetyRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ShippingRoute: typeof ShippingRoute
  TermsRoute: typeof TermsRoute
  TestStateRoute: typeof TestStateRoute
  AdminCommandRoute: typeof AdminCommandRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPharmacyRoute: typeof AdminPharmacyRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRouteWithChildren
  AdminTeamRoute: typeof AdminTeamRoute
  CheckoutUITemplate3Route: typeof CheckoutUITemplate3Route
  CheckoutChargedBeforeRoute: typeof CheckoutChargedBeforeRoute
  CheckoutTrimrxRoute: typeof CheckoutTrimrxRoute
  IntakeNewWeightlossOursRoute: typeof IntakeNewWeightlossOursRoute
  IntakeWeightLossRoute: typeof IntakeWeightLossRoute
  IntakeWeightLossTrimrxRoute: typeof IntakeWeightLossTrimrxRoute
  IntakeWeightLossTrimrx2Route: typeof IntakeWeightLossTrimrx2Route
  IntakeWeightloss3Route: typeof IntakeWeightloss3Route
  OperatorDashboardRoute: typeof OperatorDashboardRoute
  OperatorLoginRoute: typeof OperatorLoginRoute
  PharmacyLoginRoute: typeof PharmacyLoginRoute
  PharmacyMeRoute: typeof PharmacyMeRoute
  PortalPatientRoute: typeof PortalPatientRoute
  PortalPhysicianRoute: typeof PortalPhysicianRoute
  SalesDMRoute: typeof SalesDMRoute
  SalesTrimrxRoute: typeof SalesTrimrxRoute
  WeightLossSalesRoute: typeof WeightLossSalesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  OperatorIndexRoute: typeof OperatorIndexRoute
  WeightLossIndexRoute: typeof WeightLossIndexRoute
  AdminAnalyticsAcquisitionRoute: typeof AdminAnalyticsAcquisitionRoute
  AdminAnalyticsFinancesRoute: typeof AdminAnalyticsFinancesRoute
  AdminAnalyticsFunnelRoute: typeof AdminAnalyticsFunnelRoute
  AdminAnalyticsRetentionRoute: typeof AdminAnalyticsRetentionRoute
  AdminBuildEmailsRoute: typeof AdminBuildEmailsRoute
  AdminBuildFunnelRoute: typeof AdminBuildFunnelRoute
  AdminBuildIntakeRoute: typeof AdminBuildIntakeRoute
  AdminBuildPagesRoute: typeof AdminBuildPagesRoute
  AdminBuildProductsRoute: typeof AdminBuildProductsRoute
  AdminCheckInsIdRoute: typeof AdminCheckInsIdRoute
  AdminIntegrationsIdRoute: typeof AdminIntegrationsIdRoute
  AdminLeadsIdRoute: typeof AdminLeadsIdRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
  AdminPhysicianQueueIdRoute: typeof AdminPhysicianQueueIdRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminCheckInsIndexRoute: typeof AdminCheckInsIndexRoute
  AdminIntegrationsIndexRoute: typeof AdminIntegrationsIndexRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminPatientsIndexRoute: typeof AdminPatientsIndexRoute
  AdminPhysicianQueueIndexRoute: typeof AdminPhysicianQueueIndexRoute
  PharmacyOrdersIndexRoute: typeof PharmacyOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-state': {
      id: '/test-state'
      path: '/test-state'
      fullPath: '/test-state'
      preLoaderRoute: typeof TestStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medication-safety': {
      id: '/medication-safety'
      path: '/medication-safety'
      fullPath: '/medication-safety'
      preLoaderRoute: typeof MedicationSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation-charged': {
      id: '/confirmation-charged'
      path: '/confirmation-charged'
      fullPath: '/confirmation-charged'
      preLoaderRoute: typeof ConfirmationChargedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight-loss/': {
      id: '/weight-loss/'
      path: '/weight-loss'
      fullPath: '/weight-loss/'
      preLoaderRoute: typeof WeightLossIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/': {
      id: '/operator/'
      path: '/operator'
      fullPath: '/operator/'
      preLoaderRoute: typeof OperatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight-loss/sales': {
      id: '/weight-loss/sales'
      path: '/weight-loss/sales'
      fullPath: '/weight-loss/sales'
      preLoaderRoute: typeof WeightLossSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/trimrx': {
      id: '/sales/trimrx'
      path: '/sales/trimrx'
      fullPath: '/sales/trimrx'
      preLoaderRoute: typeof SalesTrimrxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/DM': {
      id: '/sales/DM'
      path: '/sales/DM'
      fullPath: '/sales/DM'
      preLoaderRoute: typeof SalesDMRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/physician': {
      id: '/portal/physician'
      path: '/portal/physician'
      fullPath: '/portal/physician'
      preLoaderRoute: typeof PortalPhysicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/patient': {
      id: '/portal/patient'
      path: '/portal/patient'
      fullPath: '/portal/patient'
      preLoaderRoute: typeof PortalPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/me': {
      id: '/pharmacy/me'
      path: '/pharmacy/me'
      fullPath: '/pharmacy/me'
      preLoaderRoute: typeof PharmacyMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/login': {
      id: '/pharmacy/login'
      path: '/pharmacy/login'
      fullPath: '/pharmacy/login'
      preLoaderRoute: typeof PharmacyLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/login': {
      id: '/operator/login'
      path: '/operator/login'
      fullPath: '/operator/login'
      preLoaderRoute: typeof OperatorLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operator/dashboard': {
      id: '/operator/dashboard'
      path: '/operator/dashboard'
      fullPath: '/operator/dashboard'
      preLoaderRoute: typeof OperatorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/physician': {
      id: '/login/physician'
      path: '/physician'
      fullPath: '/login/physician'
      preLoaderRoute: typeof LoginPhysicianRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof LoginRoute
    }
    '/intake_/weightloss-3': {
      id: '/intake_/weightloss-3'
      path: '/intake/weightloss-3'
      fullPath: '/intake/weightloss-3'
      preLoaderRoute: typeof IntakeWeightloss3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake_/weight-loss-trimrx-2': {
      id: '/intake_/weight-loss-trimrx-2'
      path: '/intake/weight-loss-trimrx-2'
      fullPath: '/intake/weight-loss-trimrx-2'
      preLoaderRoute: typeof IntakeWeightLossTrimrx2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake_/weight-loss-trimrx': {
      id: '/intake_/weight-loss-trimrx'
      path: '/intake/weight-loss-trimrx'
      fullPath: '/intake/weight-loss-trimrx'
      preLoaderRoute: typeof IntakeWeightLossTrimrxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake_/weight-loss': {
      id: '/intake_/weight-loss'
      path: '/intake/weight-loss'
      fullPath: '/intake/weight-loss'
      preLoaderRoute: typeof IntakeWeightLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake_/new-weightloss-ours': {
      id: '/intake_/new-weightloss-ours'
      path: '/intake/new-weightloss-ours'
      fullPath: '/intake/new-weightloss-ours'
      preLoaderRoute: typeof IntakeNewWeightlossOursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/trimrx': {
      id: '/checkout/trimrx'
      path: '/checkout/trimrx'
      fullPath: '/checkout/trimrx'
      preLoaderRoute: typeof CheckoutTrimrxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/charged-before': {
      id: '/checkout/charged-before'
      path: '/checkout/charged-before'
      fullPath: '/checkout/charged-before'
      preLoaderRoute: typeof CheckoutChargedBeforeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/UI-template3': {
      id: '/checkout/UI-template3'
      path: '/checkout/UI-template3'
      fullPath: '/checkout/UI-template3'
      preLoaderRoute: typeof CheckoutUITemplate3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pharmacy': {
      id: '/admin/pharmacy'
      path: '/admin/pharmacy'
      fullPath: '/admin/pharmacy'
      preLoaderRoute: typeof AdminPharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/admin/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/command': {
      id: '/admin/command'
      path: '/admin/command'
      fullPath: '/admin/command'
      preLoaderRoute: typeof AdminCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pharmacy/orders/': {
      id: '/pharmacy/orders/'
      path: '/pharmacy/orders'
      fullPath: '/pharmacy/orders/'
      preLoaderRoute: typeof PharmacyOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/': {
      id: '/admin/settings/'
      path: '/'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminSettingsIndexRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/physician-queue/': {
      id: '/admin/physician-queue/'
      path: '/admin/physician-queue'
      fullPath: '/admin/physician-queue/'
      preLoaderRoute: typeof AdminPhysicianQueueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients/': {
      id: '/admin/patients/'
      path: '/admin/patients'
      fullPath: '/admin/patients/'
      preLoaderRoute: typeof AdminPatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/admin/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations/': {
      id: '/admin/integrations/'
      path: '/admin/integrations'
      fullPath: '/admin/integrations/'
      preLoaderRoute: typeof AdminIntegrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/check-ins/': {
      id: '/admin/check-ins/'
      path: '/admin/check-ins'
      fullPath: '/admin/check-ins/'
      preLoaderRoute: typeof AdminCheckInsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/admin/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings/team': {
      id: '/admin/settings/team'
      path: '/team'
      fullPath: '/admin/settings/team'
      preLoaderRoute: typeof AdminSettingsTeamRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/states': {
      id: '/admin/settings/states'
      path: '/states'
      fullPath: '/admin/settings/states'
      preLoaderRoute: typeof AdminSettingsStatesRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/plan-billing': {
      id: '/admin/settings/plan-billing'
      path: '/plan-billing'
      fullPath: '/admin/settings/plan-billing'
      preLoaderRoute: typeof AdminSettingsPlanBillingRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/pharmacy-routing': {
      id: '/admin/settings/pharmacy-routing'
      path: '/pharmacy-routing'
      fullPath: '/admin/settings/pharmacy-routing'
      preLoaderRoute: typeof AdminSettingsPharmacyRoutingRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/notifications': {
      id: '/admin/settings/notifications'
      path: '/notifications'
      fullPath: '/admin/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/legal': {
      id: '/admin/settings/legal'
      path: '/legal'
      fullPath: '/admin/settings/legal'
      preLoaderRoute: typeof AdminSettingsLegalRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/integrations': {
      id: '/admin/settings/integrations'
      path: '/integrations'
      fullPath: '/admin/settings/integrations'
      preLoaderRoute: typeof AdminSettingsIntegrationsRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/general': {
      id: '/admin/settings/general'
      path: '/general'
      fullPath: '/admin/settings/general'
      preLoaderRoute: typeof AdminSettingsGeneralRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/settings/compliance': {
      id: '/admin/settings/compliance'
      path: '/compliance'
      fullPath: '/admin/settings/compliance'
      preLoaderRoute: typeof AdminSettingsComplianceRouteImport
      parentRoute: typeof AdminSettingsRoute
    }
    '/admin/physician-queue/$id': {
      id: '/admin/physician-queue/$id'
      path: '/admin/physician-queue/$id'
      fullPath: '/admin/physician-queue/$id'
      preLoaderRoute: typeof AdminPhysicianQueueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients/$id': {
      id: '/admin/patients/$id'
      path: '/admin/patients/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads/$id': {
      id: '/admin/leads/$id'
      path: '/admin/leads/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AdminLeadsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations/$id': {
      id: '/admin/integrations/$id'
      path: '/admin/integrations/$id'
      fullPath: '/admin/integrations/$id'
      preLoaderRoute: typeof AdminIntegrationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/check-ins/$id': {
      id: '/admin/check-ins/$id'
      path: '/admin/check-ins/$id'
      fullPath: '/admin/check-ins/$id'
      preLoaderRoute: typeof AdminCheckInsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/build/products': {
      id: '/admin/build/products'
      path: '/admin/build/products'
      fullPath: '/admin/build/products'
      preLoaderRoute: typeof AdminBuildProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/build/pages': {
      id: '/admin/build/pages'
      path: '/admin/build/pages'
      fullPath: '/admin/build/pages'
      preLoaderRoute: typeof AdminBuildPagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/build/intake': {
      id: '/admin/build/intake'
      path: '/admin/build/intake'
      fullPath: '/admin/build/intake'
      preLoaderRoute: typeof AdminBuildIntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/build/funnel': {
      id: '/admin/build/funnel'
      path: '/admin/build/funnel'
      fullPath: '/admin/build/funnel'
      preLoaderRoute: typeof AdminBuildFunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/build/emails': {
      id: '/admin/build/emails'
      path: '/admin/build/emails'
      fullPath: '/admin/build/emails'
      preLoaderRoute: typeof AdminBuildEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics/retention': {
      id: '/admin/analytics/retention'
      path: '/admin/analytics/retention'
      fullPath: '/admin/analytics/retention'
      preLoaderRoute: typeof AdminAnalyticsRetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics/funnel': {
      id: '/admin/analytics/funnel'
      path: '/admin/analytics/funnel'
      fullPath: '/admin/analytics/funnel'
      preLoaderRoute: typeof AdminAnalyticsFunnelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics/finances': {
      id: '/admin/analytics/finances'
      path: '/admin/analytics/finances'
      fullPath: '/admin/analytics/finances'
      preLoaderRoute: typeof AdminAnalyticsFinancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics/acquisition': {
      id: '/admin/analytics/acquisition'
      path: '/admin/analytics/acquisition'
      fullPath: '/admin/analytics/acquisition'
      preLoaderRoute: typeof AdminAnalyticsAcquisitionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LoginRouteChildren {
  LoginAdminRoute: typeof LoginAdminRoute
  LoginPhysicianRoute: typeof LoginPhysicianRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginAdminRoute: LoginAdminRoute,
  LoginPhysicianRoute: LoginPhysicianRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface AdminSettingsRouteChildren {
  AdminSettingsComplianceRoute: typeof AdminSettingsComplianceRoute
  AdminSettingsGeneralRoute: typeof AdminSettingsGeneralRoute
  AdminSettingsIntegrationsRoute: typeof AdminSettingsIntegrationsRoute
  AdminSettingsLegalRoute: typeof AdminSettingsLegalRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsPharmacyRoutingRoute: typeof AdminSettingsPharmacyRoutingRoute
  AdminSettingsPlanBillingRoute: typeof AdminSettingsPlanBillingRoute
  AdminSettingsStatesRoute: typeof AdminSettingsStatesRoute
  AdminSettingsTeamRoute: typeof AdminSettingsTeamRoute
  AdminSettingsIndexRoute: typeof AdminSettingsIndexRoute
}

const AdminSettingsRouteChildren: AdminSettingsRouteChildren = {
  AdminSettingsComplianceRoute: AdminSettingsComplianceRoute,
  AdminSettingsGeneralRoute: AdminSettingsGeneralRoute,
  AdminSettingsIntegrationsRoute: AdminSettingsIntegrationsRoute,
  AdminSettingsLegalRoute: AdminSettingsLegalRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsPharmacyRoutingRoute: AdminSettingsPharmacyRoutingRoute,
  AdminSettingsPlanBillingRoute: AdminSettingsPlanBillingRoute,
  AdminSettingsStatesRoute: AdminSettingsStatesRoute,
  AdminSettingsTeamRoute: AdminSettingsTeamRoute,
  AdminSettingsIndexRoute: AdminSettingsIndexRoute,
}

const AdminSettingsRouteWithChildren = AdminSettingsRoute._addFileChildren(
  AdminSettingsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmationRoute: ConfirmationRoute,
  ConfirmationChargedRoute: ConfirmationChargedRoute,
  EmailsRoute: EmailsRoute,
  IntakeRoute: IntakeRoute,
  LoginRoute: LoginRouteWithChildren,
  MedicationSafetyRoute: MedicationSafetyRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ShippingRoute: ShippingRoute,
  TermsRoute: TermsRoute,
  TestStateRoute: TestStateRoute,
  AdminCommandRoute: AdminCommandRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPharmacyRoute: AdminPharmacyRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRouteWithChildren,
  AdminTeamRoute: AdminTeamRoute,
  CheckoutUITemplate3Route: CheckoutUITemplate3Route,
  CheckoutChargedBeforeRoute: CheckoutChargedBeforeRoute,
  CheckoutTrimrxRoute: CheckoutTrimrxRoute,
  IntakeNewWeightlossOursRoute: IntakeNewWeightlossOursRoute,
  IntakeWeightLossRoute: IntakeWeightLossRoute,
  IntakeWeightLossTrimrxRoute: IntakeWeightLossTrimrxRoute,
  IntakeWeightLossTrimrx2Route: IntakeWeightLossTrimrx2Route,
  IntakeWeightloss3Route: IntakeWeightloss3Route,
  OperatorDashboardRoute: OperatorDashboardRoute,
  OperatorLoginRoute: OperatorLoginRoute,
  PharmacyLoginRoute: PharmacyLoginRoute,
  PharmacyMeRoute: PharmacyMeRoute,
  PortalPatientRoute: PortalPatientRoute,
  PortalPhysicianRoute: PortalPhysicianRoute,
  SalesDMRoute: SalesDMRoute,
  SalesTrimrxRoute: SalesTrimrxRoute,
  WeightLossSalesRoute: WeightLossSalesRoute,
  AdminIndexRoute: AdminIndexRoute,
  OperatorIndexRoute: OperatorIndexRoute,
  WeightLossIndexRoute: WeightLossIndexRoute,
  AdminAnalyticsAcquisitionRoute: AdminAnalyticsAcquisitionRoute,
  AdminAnalyticsFinancesRoute: AdminAnalyticsFinancesRoute,
  AdminAnalyticsFunnelRoute: AdminAnalyticsFunnelRoute,
  AdminAnalyticsRetentionRoute: AdminAnalyticsRetentionRoute,
  AdminBuildEmailsRoute: AdminBuildEmailsRoute,
  AdminBuildFunnelRoute: AdminBuildFunnelRoute,
  AdminBuildIntakeRoute: AdminBuildIntakeRoute,
  AdminBuildPagesRoute: AdminBuildPagesRoute,
  AdminBuildProductsRoute: AdminBuildProductsRoute,
  AdminCheckInsIdRoute: AdminCheckInsIdRoute,
  AdminIntegrationsIdRoute: AdminIntegrationsIdRoute,
  AdminLeadsIdRoute: AdminLeadsIdRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminPatientsIdRoute: AdminPatientsIdRoute,
  AdminPhysicianQueueIdRoute: AdminPhysicianQueueIdRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminCheckInsIndexRoute: AdminCheckInsIndexRoute,
  AdminIntegrationsIndexRoute: AdminIntegrationsIndexRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminPatientsIndexRoute: AdminPatientsIndexRoute,
  AdminPhysicianQueueIndexRoute: AdminPhysicianQueueIndexRoute,
  PharmacyOrdersIndexRoute: PharmacyOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
