/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestStateRouteImport } from './routes/test-state'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MedicationSafetyRouteImport } from './routes/medication-safety'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as EmailsRouteImport } from './routes/emails'
import { Route as ConfirmationChargedRouteImport } from './routes/confirmation-charged'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WeightLossIndexRouteImport } from './routes/weight-loss.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as WeightLossSalesRouteImport } from './routes/weight-loss.sales'
import { Route as SalesTrimrxRouteImport } from './routes/sales.trimrx'
import { Route as SalesDMRouteImport } from './routes/sales.DM'
import { Route as PortalPhysicianRouteImport } from './routes/portal.physician'
import { Route as PortalPatientRouteImport } from './routes/portal.patient'
import { Route as LoginPhysicianRouteImport } from './routes/login.physician'
import { Route as LoginAdminRouteImport } from './routes/login.admin'
import { Route as IntakeWeightloss3RouteImport } from './routes/intake_.weightloss-3'
import { Route as IntakeWeightLossTrimrx2RouteImport } from './routes/intake_.weight-loss-trimrx-2'
import { Route as IntakeWeightLossTrimrxRouteImport } from './routes/intake_.weight-loss-trimrx'
import { Route as IntakeWeightLossRouteImport } from './routes/intake_.weight-loss'
import { Route as IntakeNewWeightlossOursRouteImport } from './routes/intake_.new-weightloss-ours'
import { Route as CheckoutTrimrxRouteImport } from './routes/checkout.trimrx'
import { Route as CheckoutChargedBeforeRouteImport } from './routes/checkout.charged-before'
import { Route as CheckoutUITemplate3RouteImport } from './routes/checkout.UI-template3'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPhysicianQueueRouteImport } from './routes/admin.physician-queue'
import { Route as AdminPharmacyRouteImport } from './routes/admin.pharmacy'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPatientsRouteImport } from './routes/admin.patients'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminMessagesRouteImport } from './routes/admin.messages'
import { Route as AdminLiveRouteImport } from './routes/admin.live'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminIntegrationsRouteImport } from './routes/admin.integrations'
import { Route as AdminCommandRouteImport } from './routes/admin.command'
import { Route as AdminCheckInsRouteImport } from './routes/admin.check-ins'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminPatientsIdRouteImport } from './routes/admin.patients.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminAnalyticsRetentionRouteImport } from './routes/admin.analytics.retention'
import { Route as AdminAnalyticsFunnelRouteImport } from './routes/admin.analytics.funnel'
import { Route as AdminAnalyticsFinancesRouteImport } from './routes/admin.analytics.finances'
import { Route as AdminAnalyticsAcquisitionRouteImport } from './routes/admin.analytics.acquisition'

const TestStateRoute = TestStateRouteImport.update({
  id: '/test-state',
  path: '/test-state',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationSafetyRoute = MedicationSafetyRouteImport.update({
  id: '/medication-safety',
  path: '/medication-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailsRoute = EmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationChargedRoute = ConfirmationChargedRouteImport.update({
  id: '/confirmation-charged',
  path: '/confirmation-charged',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightLossIndexRoute = WeightLossIndexRouteImport.update({
  id: '/weight-loss/',
  path: '/weight-loss/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const WeightLossSalesRoute = WeightLossSalesRouteImport.update({
  id: '/weight-loss/sales',
  path: '/weight-loss/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesTrimrxRoute = SalesTrimrxRouteImport.update({
  id: '/sales/trimrx',
  path: '/sales/trimrx',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesDMRoute = SalesDMRouteImport.update({
  id: '/sales/DM',
  path: '/sales/DM',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPhysicianRoute = PortalPhysicianRouteImport.update({
  id: '/portal/physician',
  path: '/portal/physician',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPatientRoute = PortalPatientRouteImport.update({
  id: '/portal/patient',
  path: '/portal/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPhysicianRoute = LoginPhysicianRouteImport.update({
  id: '/physician',
  path: '/physician',
  getParentRoute: () => LoginRoute,
} as any)
const LoginAdminRoute = LoginAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LoginRoute,
} as any)
const IntakeWeightloss3Route = IntakeWeightloss3RouteImport.update({
  id: '/intake_/weightloss-3',
  path: '/intake/weightloss-3',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeWeightLossTrimrx2Route = IntakeWeightLossTrimrx2RouteImport.update({
  id: '/intake_/weight-loss-trimrx-2',
  path: '/intake/weight-loss-trimrx-2',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeWeightLossTrimrxRoute = IntakeWeightLossTrimrxRouteImport.update({
  id: '/intake_/weight-loss-trimrx',
  path: '/intake/weight-loss-trimrx',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeWeightLossRoute = IntakeWeightLossRouteImport.update({
  id: '/intake_/weight-loss',
  path: '/intake/weight-loss',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeNewWeightlossOursRoute = IntakeNewWeightlossOursRouteImport.update({
  id: '/intake_/new-weightloss-ours',
  path: '/intake/new-weightloss-ours',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTrimrxRoute = CheckoutTrimrxRouteImport.update({
  id: '/checkout/trimrx',
  path: '/checkout/trimrx',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutChargedBeforeRoute = CheckoutChargedBeforeRouteImport.update({
  id: '/checkout/charged-before',
  path: '/checkout/charged-before',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutUITemplate3Route = CheckoutUITemplate3RouteImport.update({
  id: '/checkout/UI-template3',
  path: '/checkout/UI-template3',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/admin/team',
  path: '/admin/team',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPhysicianQueueRoute = AdminPhysicianQueueRouteImport.update({
  id: '/admin/physician-queue',
  path: '/admin/physician-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPharmacyRoute = AdminPharmacyRouteImport.update({
  id: '/admin/pharmacy',
  path: '/admin/pharmacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMessagesRoute = AdminMessagesRouteImport.update({
  id: '/admin/messages',
  path: '/admin/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/admin/live',
  path: '/admin/live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommandRoute = AdminCommandRouteImport.update({
  id: '/admin/command',
  path: '/admin/command',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCheckInsRoute = AdminCheckInsRouteImport.update({
  id: '/admin/check-ins',
  path: '/admin/check-ins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsIdRoute = AdminPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPatientsRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminAnalyticsRetentionRoute = AdminAnalyticsRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsFunnelRoute = AdminAnalyticsFunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsFinancesRoute = AdminAnalyticsFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => AdminAnalyticsRoute,
} as any)
const AdminAnalyticsAcquisitionRoute =
  AdminAnalyticsAcquisitionRouteImport.update({
    id: '/acquisition',
    path: '/acquisition',
    getParentRoute: () => AdminAnalyticsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/confirmation-charged': typeof ConfirmationChargedRoute
  '/emails': typeof EmailsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRouteWithChildren
  '/medication-safety': typeof MedicationSafetyRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/test-state': typeof TestStateRoute
  '/admin/analytics': typeof AdminAnalyticsRouteWithChildren
  '/admin/check-ins': typeof AdminCheckInsRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/physician-queue': typeof AdminPhysicianQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/checkout/UI-template3': typeof CheckoutUITemplate3Route
  '/checkout/charged-before': typeof CheckoutChargedBeforeRoute
  '/checkout/trimrx': typeof CheckoutTrimrxRoute
  '/intake/new-weightloss-ours': typeof IntakeNewWeightlossOursRoute
  '/intake/weight-loss': typeof IntakeWeightLossRoute
  '/intake/weight-loss-trimrx': typeof IntakeWeightLossTrimrxRoute
  '/intake/weight-loss-trimrx-2': typeof IntakeWeightLossTrimrx2Route
  '/intake/weightloss-3': typeof IntakeWeightloss3Route
  '/login/admin': typeof LoginAdminRoute
  '/login/physician': typeof LoginPhysicianRoute
  '/portal/patient': typeof PortalPatientRoute
  '/portal/physician': typeof PortalPhysicianRoute
  '/sales/DM': typeof SalesDMRoute
  '/sales/trimrx': typeof SalesTrimrxRoute
  '/weight-loss/sales': typeof WeightLossSalesRoute
  '/admin/': typeof AdminIndexRoute
  '/weight-loss/': typeof WeightLossIndexRoute
  '/admin/analytics/acquisition': typeof AdminAnalyticsAcquisitionRoute
  '/admin/analytics/finances': typeof AdminAnalyticsFinancesRoute
  '/admin/analytics/funnel': typeof AdminAnalyticsFunnelRoute
  '/admin/analytics/retention': typeof AdminAnalyticsRetentionRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/confirmation-charged': typeof ConfirmationChargedRoute
  '/emails': typeof EmailsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRouteWithChildren
  '/medication-safety': typeof MedicationSafetyRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/test-state': typeof TestStateRoute
  '/admin/analytics': typeof AdminAnalyticsRouteWithChildren
  '/admin/check-ins': typeof AdminCheckInsRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/physician-queue': typeof AdminPhysicianQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/checkout/UI-template3': typeof CheckoutUITemplate3Route
  '/checkout/charged-before': typeof CheckoutChargedBeforeRoute
  '/checkout/trimrx': typeof CheckoutTrimrxRoute
  '/intake/new-weightloss-ours': typeof IntakeNewWeightlossOursRoute
  '/intake/weight-loss': typeof IntakeWeightLossRoute
  '/intake/weight-loss-trimrx': typeof IntakeWeightLossTrimrxRoute
  '/intake/weight-loss-trimrx-2': typeof IntakeWeightLossTrimrx2Route
  '/intake/weightloss-3': typeof IntakeWeightloss3Route
  '/login/admin': typeof LoginAdminRoute
  '/login/physician': typeof LoginPhysicianRoute
  '/portal/patient': typeof PortalPatientRoute
  '/portal/physician': typeof PortalPhysicianRoute
  '/sales/DM': typeof SalesDMRoute
  '/sales/trimrx': typeof SalesTrimrxRoute
  '/weight-loss/sales': typeof WeightLossSalesRoute
  '/admin': typeof AdminIndexRoute
  '/weight-loss': typeof WeightLossIndexRoute
  '/admin/analytics/acquisition': typeof AdminAnalyticsAcquisitionRoute
  '/admin/analytics/finances': typeof AdminAnalyticsFinancesRoute
  '/admin/analytics/funnel': typeof AdminAnalyticsFunnelRoute
  '/admin/analytics/retention': typeof AdminAnalyticsRetentionRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/confirmation-charged': typeof ConfirmationChargedRoute
  '/emails': typeof EmailsRoute
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRouteWithChildren
  '/medication-safety': typeof MedicationSafetyRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/shipping': typeof ShippingRoute
  '/terms': typeof TermsRoute
  '/test-state': typeof TestStateRoute
  '/admin/analytics': typeof AdminAnalyticsRouteWithChildren
  '/admin/check-ins': typeof AdminCheckInsRoute
  '/admin/command': typeof AdminCommandRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/messages': typeof AdminMessagesRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/patients': typeof AdminPatientsRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pharmacy': typeof AdminPharmacyRoute
  '/admin/physician-queue': typeof AdminPhysicianQueueRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/team': typeof AdminTeamRoute
  '/checkout/UI-template3': typeof CheckoutUITemplate3Route
  '/checkout/charged-before': typeof CheckoutChargedBeforeRoute
  '/checkout/trimrx': typeof CheckoutTrimrxRoute
  '/intake_/new-weightloss-ours': typeof IntakeNewWeightlossOursRoute
  '/intake_/weight-loss': typeof IntakeWeightLossRoute
  '/intake_/weight-loss-trimrx': typeof IntakeWeightLossTrimrxRoute
  '/intake_/weight-loss-trimrx-2': typeof IntakeWeightLossTrimrx2Route
  '/intake_/weightloss-3': typeof IntakeWeightloss3Route
  '/login/admin': typeof LoginAdminRoute
  '/login/physician': typeof LoginPhysicianRoute
  '/portal/patient': typeof PortalPatientRoute
  '/portal/physician': typeof PortalPhysicianRoute
  '/sales/DM': typeof SalesDMRoute
  '/sales/trimrx': typeof SalesTrimrxRoute
  '/weight-loss/sales': typeof WeightLossSalesRoute
  '/admin/': typeof AdminIndexRoute
  '/weight-loss/': typeof WeightLossIndexRoute
  '/admin/analytics/acquisition': typeof AdminAnalyticsAcquisitionRoute
  '/admin/analytics/finances': typeof AdminAnalyticsFinancesRoute
  '/admin/analytics/funnel': typeof AdminAnalyticsFunnelRoute
  '/admin/analytics/retention': typeof AdminAnalyticsRetentionRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/patients/$id': typeof AdminPatientsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmation'
    | '/confirmation-charged'
    | '/emails'
    | '/intake'
    | '/login'
    | '/medication-safety'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/terms'
    | '/test-state'
    | '/admin/analytics'
    | '/admin/check-ins'
    | '/admin/command'
    | '/admin/integrations'
    | '/admin/leads'
    | '/admin/live'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/patients'
    | '/admin/payments'
    | '/admin/pharmacy'
    | '/admin/physician-queue'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/team'
    | '/checkout/UI-template3'
    | '/checkout/charged-before'
    | '/checkout/trimrx'
    | '/intake/new-weightloss-ours'
    | '/intake/weight-loss'
    | '/intake/weight-loss-trimrx'
    | '/intake/weight-loss-trimrx-2'
    | '/intake/weightloss-3'
    | '/login/admin'
    | '/login/physician'
    | '/portal/patient'
    | '/portal/physician'
    | '/sales/DM'
    | '/sales/trimrx'
    | '/weight-loss/sales'
    | '/admin/'
    | '/weight-loss/'
    | '/admin/analytics/acquisition'
    | '/admin/analytics/finances'
    | '/admin/analytics/funnel'
    | '/admin/analytics/retention'
    | '/admin/orders/$id'
    | '/admin/patients/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmation'
    | '/confirmation-charged'
    | '/emails'
    | '/intake'
    | '/login'
    | '/medication-safety'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/terms'
    | '/test-state'
    | '/admin/analytics'
    | '/admin/check-ins'
    | '/admin/command'
    | '/admin/integrations'
    | '/admin/leads'
    | '/admin/live'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/patients'
    | '/admin/payments'
    | '/admin/pharmacy'
    | '/admin/physician-queue'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/team'
    | '/checkout/UI-template3'
    | '/checkout/charged-before'
    | '/checkout/trimrx'
    | '/intake/new-weightloss-ours'
    | '/intake/weight-loss'
    | '/intake/weight-loss-trimrx'
    | '/intake/weight-loss-trimrx-2'
    | '/intake/weightloss-3'
    | '/login/admin'
    | '/login/physician'
    | '/portal/patient'
    | '/portal/physician'
    | '/sales/DM'
    | '/sales/trimrx'
    | '/weight-loss/sales'
    | '/admin'
    | '/weight-loss'
    | '/admin/analytics/acquisition'
    | '/admin/analytics/finances'
    | '/admin/analytics/funnel'
    | '/admin/analytics/retention'
    | '/admin/orders/$id'
    | '/admin/patients/$id'
  id:
    | '__root__'
    | '/'
    | '/confirmation'
    | '/confirmation-charged'
    | '/emails'
    | '/intake'
    | '/login'
    | '/medication-safety'
    | '/privacy'
    | '/refund'
    | '/shipping'
    | '/terms'
    | '/test-state'
    | '/admin/analytics'
    | '/admin/check-ins'
    | '/admin/command'
    | '/admin/integrations'
    | '/admin/leads'
    | '/admin/live'
    | '/admin/messages'
    | '/admin/orders'
    | '/admin/patients'
    | '/admin/payments'
    | '/admin/pharmacy'
    | '/admin/physician-queue'
    | '/admin/reports'
    | '/admin/settings'
    | '/admin/team'
    | '/checkout/UI-template3'
    | '/checkout/charged-before'
    | '/checkout/trimrx'
    | '/intake_/new-weightloss-ours'
    | '/intake_/weight-loss'
    | '/intake_/weight-loss-trimrx'
    | '/intake_/weight-loss-trimrx-2'
    | '/intake_/weightloss-3'
    | '/login/admin'
    | '/login/physician'
    | '/portal/patient'
    | '/portal/physician'
    | '/sales/DM'
    | '/sales/trimrx'
    | '/weight-loss/sales'
    | '/admin/'
    | '/weight-loss/'
    | '/admin/analytics/acquisition'
    | '/admin/analytics/finances'
    | '/admin/analytics/funnel'
    | '/admin/analytics/retention'
    | '/admin/orders/$id'
    | '/admin/patients/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ConfirmationChargedRoute: typeof ConfirmationChargedRoute
  EmailsRoute: typeof EmailsRoute
  IntakeRoute: typeof IntakeRoute
  LoginRoute: typeof LoginRouteWithChildren
  MedicationSafetyRoute: typeof MedicationSafetyRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ShippingRoute: typeof ShippingRoute
  TermsRoute: typeof TermsRoute
  TestStateRoute: typeof TestStateRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRouteWithChildren
  AdminCheckInsRoute: typeof AdminCheckInsRoute
  AdminCommandRoute: typeof AdminCommandRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminMessagesRoute: typeof AdminMessagesRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPatientsRoute: typeof AdminPatientsRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPharmacyRoute: typeof AdminPharmacyRoute
  AdminPhysicianQueueRoute: typeof AdminPhysicianQueueRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  CheckoutUITemplate3Route: typeof CheckoutUITemplate3Route
  CheckoutChargedBeforeRoute: typeof CheckoutChargedBeforeRoute
  CheckoutTrimrxRoute: typeof CheckoutTrimrxRoute
  IntakeNewWeightlossOursRoute: typeof IntakeNewWeightlossOursRoute
  IntakeWeightLossRoute: typeof IntakeWeightLossRoute
  IntakeWeightLossTrimrxRoute: typeof IntakeWeightLossTrimrxRoute
  IntakeWeightLossTrimrx2Route: typeof IntakeWeightLossTrimrx2Route
  IntakeWeightloss3Route: typeof IntakeWeightloss3Route
  PortalPatientRoute: typeof PortalPatientRoute
  PortalPhysicianRoute: typeof PortalPhysicianRoute
  SalesDMRoute: typeof SalesDMRoute
  SalesTrimrxRoute: typeof SalesTrimrxRoute
  WeightLossSalesRoute: typeof WeightLossSalesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  WeightLossIndexRoute: typeof WeightLossIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test-state': {
      id: '/test-state'
      path: '/test-state'
      fullPath: '/test-state'
      preLoaderRoute: typeof TestStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medication-safety': {
      id: '/medication-safety'
      path: '/medication-safety'
      fullPath: '/medication-safety'
      preLoaderRoute: typeof MedicationSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emails': {
      id: '/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof EmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation-charged': {
      id: '/confirmation-charged'
      path: '/confirmation-charged'
      fullPath: '/confirmation-charged'
      preLoaderRoute: typeof ConfirmationChargedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight-loss/': {
      id: '/weight-loss/'
      path: '/weight-loss'
      fullPath: '/weight-loss/'
      preLoaderRoute: typeof WeightLossIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weight-loss/sales': {
      id: '/weight-loss/sales'
      path: '/weight-loss/sales'
      fullPath: '/weight-loss/sales'
      preLoaderRoute: typeof WeightLossSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/trimrx': {
      id: '/sales/trimrx'
      path: '/sales/trimrx'
      fullPath: '/sales/trimrx'
      preLoaderRoute: typeof SalesTrimrxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales/DM': {
      id: '/sales/DM'
      path: '/sales/DM'
      fullPath: '/sales/DM'
      preLoaderRoute: typeof SalesDMRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/physician': {
      id: '/portal/physician'
      path: '/portal/physician'
      fullPath: '/portal/physician'
      preLoaderRoute: typeof PortalPhysicianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/patient': {
      id: '/portal/patient'
      path: '/portal/patient'
      fullPath: '/portal/patient'
      preLoaderRoute: typeof PortalPatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/physician': {
      id: '/login/physician'
      path: '/physician'
      fullPath: '/login/physician'
      preLoaderRoute: typeof LoginPhysicianRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/admin': {
      id: '/login/admin'
      path: '/admin'
      fullPath: '/login/admin'
      preLoaderRoute: typeof LoginAdminRouteImport
      parentRoute: typeof LoginRoute
    }
    '/intake_/weightloss-3': {
      id: '/intake_/weightloss-3'
      path: '/intake/weightloss-3'
      fullPath: '/intake/weightloss-3'
      preLoaderRoute: typeof IntakeWeightloss3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake_/weight-loss-trimrx-2': {
      id: '/intake_/weight-loss-trimrx-2'
      path: '/intake/weight-loss-trimrx-2'
      fullPath: '/intake/weight-loss-trimrx-2'
      preLoaderRoute: typeof IntakeWeightLossTrimrx2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake_/weight-loss-trimrx': {
      id: '/intake_/weight-loss-trimrx'
      path: '/intake/weight-loss-trimrx'
      fullPath: '/intake/weight-loss-trimrx'
      preLoaderRoute: typeof IntakeWeightLossTrimrxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake_/weight-loss': {
      id: '/intake_/weight-loss'
      path: '/intake/weight-loss'
      fullPath: '/intake/weight-loss'
      preLoaderRoute: typeof IntakeWeightLossRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake_/new-weightloss-ours': {
      id: '/intake_/new-weightloss-ours'
      path: '/intake/new-weightloss-ours'
      fullPath: '/intake/new-weightloss-ours'
      preLoaderRoute: typeof IntakeNewWeightlossOursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/trimrx': {
      id: '/checkout/trimrx'
      path: '/checkout/trimrx'
      fullPath: '/checkout/trimrx'
      preLoaderRoute: typeof CheckoutTrimrxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/charged-before': {
      id: '/checkout/charged-before'
      path: '/checkout/charged-before'
      fullPath: '/checkout/charged-before'
      preLoaderRoute: typeof CheckoutChargedBeforeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/UI-template3': {
      id: '/checkout/UI-template3'
      path: '/checkout/UI-template3'
      fullPath: '/checkout/UI-template3'
      preLoaderRoute: typeof CheckoutUITemplate3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/admin/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/physician-queue': {
      id: '/admin/physician-queue'
      path: '/admin/physician-queue'
      fullPath: '/admin/physician-queue'
      preLoaderRoute: typeof AdminPhysicianQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pharmacy': {
      id: '/admin/pharmacy'
      path: '/admin/pharmacy'
      fullPath: '/admin/pharmacy'
      preLoaderRoute: typeof AdminPharmacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/messages': {
      id: '/admin/messages'
      path: '/admin/messages'
      fullPath: '/admin/messages'
      preLoaderRoute: typeof AdminMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/admin/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/command': {
      id: '/admin/command'
      path: '/admin/command'
      fullPath: '/admin/command'
      preLoaderRoute: typeof AdminCommandRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/check-ins': {
      id: '/admin/check-ins'
      path: '/admin/check-ins'
      fullPath: '/admin/check-ins'
      preLoaderRoute: typeof AdminCheckInsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients/$id': {
      id: '/admin/patients/$id'
      path: '/$id'
      fullPath: '/admin/patients/$id'
      preLoaderRoute: typeof AdminPatientsIdRouteImport
      parentRoute: typeof AdminPatientsRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/analytics/retention': {
      id: '/admin/analytics/retention'
      path: '/retention'
      fullPath: '/admin/analytics/retention'
      preLoaderRoute: typeof AdminAnalyticsRetentionRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/funnel': {
      id: '/admin/analytics/funnel'
      path: '/funnel'
      fullPath: '/admin/analytics/funnel'
      preLoaderRoute: typeof AdminAnalyticsFunnelRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/finances': {
      id: '/admin/analytics/finances'
      path: '/finances'
      fullPath: '/admin/analytics/finances'
      preLoaderRoute: typeof AdminAnalyticsFinancesRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
    '/admin/analytics/acquisition': {
      id: '/admin/analytics/acquisition'
      path: '/acquisition'
      fullPath: '/admin/analytics/acquisition'
      preLoaderRoute: typeof AdminAnalyticsAcquisitionRouteImport
      parentRoute: typeof AdminAnalyticsRoute
    }
  }
}

interface LoginRouteChildren {
  LoginAdminRoute: typeof LoginAdminRoute
  LoginPhysicianRoute: typeof LoginPhysicianRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginAdminRoute: LoginAdminRoute,
  LoginPhysicianRoute: LoginPhysicianRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface AdminAnalyticsRouteChildren {
  AdminAnalyticsAcquisitionRoute: typeof AdminAnalyticsAcquisitionRoute
  AdminAnalyticsFinancesRoute: typeof AdminAnalyticsFinancesRoute
  AdminAnalyticsFunnelRoute: typeof AdminAnalyticsFunnelRoute
  AdminAnalyticsRetentionRoute: typeof AdminAnalyticsRetentionRoute
}

const AdminAnalyticsRouteChildren: AdminAnalyticsRouteChildren = {
  AdminAnalyticsAcquisitionRoute: AdminAnalyticsAcquisitionRoute,
  AdminAnalyticsFinancesRoute: AdminAnalyticsFinancesRoute,
  AdminAnalyticsFunnelRoute: AdminAnalyticsFunnelRoute,
  AdminAnalyticsRetentionRoute: AdminAnalyticsRetentionRoute,
}

const AdminAnalyticsRouteWithChildren = AdminAnalyticsRoute._addFileChildren(
  AdminAnalyticsRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminPatientsRouteChildren {
  AdminPatientsIdRoute: typeof AdminPatientsIdRoute
}

const AdminPatientsRouteChildren: AdminPatientsRouteChildren = {
  AdminPatientsIdRoute: AdminPatientsIdRoute,
}

const AdminPatientsRouteWithChildren = AdminPatientsRoute._addFileChildren(
  AdminPatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmationRoute: ConfirmationRoute,
  ConfirmationChargedRoute: ConfirmationChargedRoute,
  EmailsRoute: EmailsRoute,
  IntakeRoute: IntakeRoute,
  LoginRoute: LoginRouteWithChildren,
  MedicationSafetyRoute: MedicationSafetyRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ShippingRoute: ShippingRoute,
  TermsRoute: TermsRoute,
  TestStateRoute: TestStateRoute,
  AdminAnalyticsRoute: AdminAnalyticsRouteWithChildren,
  AdminCheckInsRoute: AdminCheckInsRoute,
  AdminCommandRoute: AdminCommandRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminMessagesRoute: AdminMessagesRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPatientsRoute: AdminPatientsRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPharmacyRoute: AdminPharmacyRoute,
  AdminPhysicianQueueRoute: AdminPhysicianQueueRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamRoute: AdminTeamRoute,
  CheckoutUITemplate3Route: CheckoutUITemplate3Route,
  CheckoutChargedBeforeRoute: CheckoutChargedBeforeRoute,
  CheckoutTrimrxRoute: CheckoutTrimrxRoute,
  IntakeNewWeightlossOursRoute: IntakeNewWeightlossOursRoute,
  IntakeWeightLossRoute: IntakeWeightLossRoute,
  IntakeWeightLossTrimrxRoute: IntakeWeightLossTrimrxRoute,
  IntakeWeightLossTrimrx2Route: IntakeWeightLossTrimrx2Route,
  IntakeWeightloss3Route: IntakeWeightloss3Route,
  PortalPatientRoute: PortalPatientRoute,
  PortalPhysicianRoute: PortalPhysicianRoute,
  SalesDMRoute: SalesDMRoute,
  SalesTrimrxRoute: SalesTrimrxRoute,
  WeightLossSalesRoute: WeightLossSalesRoute,
  AdminIndexRoute: AdminIndexRoute,
  WeightLossIndexRoute: WeightLossIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
